### ISSUE TITLE
SNES Classic (Japan) text issues

### ISSUE THREAD

**Issue by vulfgang** [DefKorns/om_theme-selector#3]
Two issues I have run into with the theme selector

1) When you do individual themes for folders when you back out it still plays the music from the last theme you were previously using

2) On the Japanese Super Famicom the text will disappear on the custom themes. I tried this with the english translation mod and without. Pictures attached. 

Side issue - the newest build of hakchi2 CE the english translation mod doesn't work, same issue as above, the text box is just a blank white box. Not important that the menus are in Japanese but it blocks my custom folder names which is a problem.

![a08c45abe4407a7cec99a3ceb1962a0d22e6c716-1](https://user-images.githubusercontent.com/47423189/52419000-30f41980-2abd-11e9-8aab-1a928895d5f6.jpg)

[hmod_audit.txt](https://github.com/DefKorns/om_theme-selector/files/2841302/hmod_audit.txt)

**Comment by DefKorns** [comment]
Hi @vulfgang,

I'm sorry you're experience issues, but i'll try to fix all your issues :)

> 1. When you do individual themes for folders when you back out it still plays the music from the last theme you were previously using

This issue was already addressed and it i'll be fixed on the next release.

Regarding the second issue, i just noticed that the Super Famicom Classc has the title text set to white 

![SFC](https://snesclassicmods.com/wp-content/uploads/2017/12/Super-Famicom-Mini-in-English.png)

Sorry i've missed that. I'm going to update the themes to include the correct color files to match all consoles. I'll keep you posted.

Now your side issue, i don't work with the HakchiCE developers, nor the creator of that script. 

If you want i can share with you my language mod (unreleased yet) that works just like theme selector and allows you to add custom languages to your console (and a couple of extra things) ;)

**Comment by vulfgang** [comment]
Thanks Def, I would really appreciate that. This one has been such a headache and I have been looking into how to get into the internal files to just swap out.

If you have a language mod that resolves this issue I would love to give it a try.
________________________________

**Comment by vulfgang** [comment]
Testing the defaultscene.zip attached. Ill get back to you this evening with the results.

**Comment by DefKorns** [comment]
@vulfgang  i'll send you the mod for language through discord
